applications:
  - name: giropops-senhas
    namespace: giropops-senhas
    repoURL: https://github.com/maxaraujo2020/descomplicando-argocd.git
    targetRevision: feature/argocd-training
    path: giropops-senhas/helm

  - name: random-logger
    namespace: random-logger
    repoURL: https://github.com/maxaraujo2020/descomplicando-argocd.git
    targetRevision: feature/argocd-training
    path: random-logger/helm
